# Generated by Django 5.0.6 on 2024-07-04 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='type',
            new_name='technique',
        ),
    ]
